### ISSUE TITLE
Pundle-related error when installing motion

### ISSUE THREAD

**Issue by liron00** [steelbrain/motion#426]
`npm install -g motion@15.0.0-beta16`

![image](https://cloud.githubusercontent.com/assets/699733/26073413/a6132eba-3963-11e7-9fc4-4b347615d0cb.png)

Then when creating a new app and running motion:
![image](https://cloud.githubusercontent.com/assets/699733/26073425/b32af330-3963-11e7-95c5-40bbbf5c577a.png)

**Comment by steelbrain** [comment]
Fixed in latest release
